version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm i
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm run audit  
